### ISSUE TITLE
Exception when running in Python3.8

### ISSUE THREAD

**Issue by alvarolopez** [indigo-dc/DEEPaaS#95]
On some Python versions replacing standard Pool to custom can raise error: AssertionError: group argument must be None for now.

This is somehow related with https://github.com/nipy/nipype/pull/2754

**Comment by aghand0ur** [comment]
@alvarolopez I had to clone from dask branch to avoid that bug:

```
022-01-10 22:12:02.232 11498 INFO deepaas [-] Starting DEEPaaS version 2.0.0.dev7
2022-01-10 22:12:02.234 11498 WARNING py.warnings [-] /home/ali/Desktop/DEEPaaS/virtualenv/lib/python3.8/site-packages/deepaas/api/__init__.py:64: DeprecationWarning: debug argument is deprecated
  APP = web.Application(debug=CONF.debug,

2022-01-10 22:12:02.246 11498 WARNING deepaas.model.v2 [-] Error loading models: No deepaas.v2.model extensions found: stevedore.exception.NoMatches: No deepaas.v2.model extensions found
2022-01-10 22:12:02.247 11498 INFO deepaas.model.v2 [-] No models found in V2, loading test model
2022-01-10 22:12:02.279 11498 ERROR asyncio [-] unhandled exception during asyncio.run() shutdown
task: <Task finished name='Task-1' coro=<_run_app() done, defined at /home/ali/Desktop/DEEPaaS/virtualenv/lib/python3.8/site-packages/aiohttp/web.py:287> exception=AssertionError('group argument must be None for now')>: AssertionError: group argument must be None for now
2022-01-10 22:12:02.279 11498 ERROR asyncio Traceback (most recent call last):
2022-01-10 22:12:02.279 11498 ERROR asyncio   File "/home/ali/Desktop/DEEPaaS/virtualenv/lib/python3.8/site-packages/aiohttp/web.py", line 514, in run_app
2022-01-10 22:12:02.279 11498 ERROR asyncio     loop.run_until_complete(main_task)
2022-01-10 22:12:02.279 11498 ERROR asyncio   File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
2022-01-10 22:12:02.279 11498 ERROR asyncio     return future.result()
2022-01-10 22:12:02.279 11498 ERROR asyncio   File "/home/ali/Desktop/DEEPaaS/virtualenv/lib/python3.8/site-packages/aiohttp/web.py", line 308, in _run_app
2022-01-10 22:12:02.279 11498 ERROR asyncio     app = await app  # type: ignore[misc]
2022-01-10 22:12:02.279 11498 ERROR asyncio   File "/home/ali/Desktop/DEEPaaS/virtualenv/lib/python3.8/site-packages/deepaas/api/__init__.py", line 70, in get_app
2022-01-10 22:12:02.279 11498 ERROR asyncio     model.register_v2_models(APP)
2022-01-10 22:12:02.279 11498 ERROR asyncio   File "/home/ali/Desktop/DEEPaaS/virtualenv/lib/python3.8/site-packages/deepaas/model/__init__.py", line 29, in register_v2_models
2022-01-10 22:12:02.279 11498 ERROR asyncio     return v2.register_models(app)
2022-01-10 22:12:02.279 11498 ERROR asyncio   File "/home/ali/Desktop/DEEPaaS/virtualenv/lib/python3.8/site-packages/deepaas/model/v2/__init__.py", line 49, in register_models
2022-01-10 22:12:02.279 11498 ERROR asyncio     MODELS["deepaas-test"] = wrapper.ModelWrapper(
2022-01-10 22:12:02.279 11498 ERROR asyncio   File "/home/ali/Desktop/DEEPaaS/virtualenv/lib/python3.8/site-packages/deepaas/model/v2/wrapper.py", line 112, in __init__
2022-01-10 22:12:02.279 11498 ERROR asyncio     self._executor = self._init_executor()
2022-01-10 22:12:02.279 11498 ERROR asyncio   File "/home/ali/Desktop/DEEPaaS/virtualenv/lib/python3.8/site-packages/deepaas/model/v2/wrapper.py", line 154, in _init_executor
2022-01-10 22:12:02.279 11498 ERROR asyncio     executor = CancellablePool(max_workers=n)
2022-01-10 22:12:02.279 11498 ERROR asyncio   File "/home/ali/Desktop/DEEPaaS/virtualenv/lib/python3.8/site-packages/deepaas/model/v2/wrapper.py", line 373, in __init__
2022-01-10 22:12:02.279 11498 ERROR asyncio     self._free = {self._new_pool() for _ in range(max_workers)}
2022-01-10 22:12:02.279 11498 ERROR asyncio   File "/home/ali/Desktop/DEEPaaS/virtualenv/lib/python3.8/site-packages/deepaas/model/v2/wrapper.py", line 373, in <setcomp>
2022-01-10 22:12:02.279 11498 ERROR asyncio     self._free = {self._new_pool() for _ in range(max_workers)}
2022-01-10 22:12:02.279 11498 ERROR asyncio   File "/home/ali/Desktop/DEEPaaS/virtualenv/lib/python3.8/site-packages/deepaas/model/v2/wrapper.py", line 378, in _new_pool
2022-01-10 22:12:02.279 11498 ERROR asyncio     return NonDaemonPool(1, context=multiprocessing.get_context('spawn'))
2022-01-10 22:12:02.279 11498 ERROR asyncio   File "/usr/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
2022-01-10 22:12:02.279 11498 ERROR asyncio     self._repopulate_pool()
2022-01-10 22:12:02.279 11498 ERROR asyncio   File "/usr/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
2022-01-10 22:12:02.279 11498 ERROR asyncio     return self._repopulate_pool_static(self._ctx, self.Process,
2022-01-10 22:12:02.279 11498 ERROR asyncio   File "/usr/lib/python3.8/multiprocessing/pool.py", line 319, in _repopulate_pool_static
2022-01-10 22:12:02.279 11498 ERROR asyncio     w = Process(ctx, target=worker,
2022-01-10 22:12:02.279 11498 ERROR asyncio   File "/usr/lib/python3.8/multiprocessing/process.py", line 82, in __init__
2022-01-10 22:12:02.279 11498 ERROR asyncio     assert group is None, 'group argument must be None for now'
2022-01-10 22:12:02.279 11498 ERROR asyncio AssertionError: group argument must be None for now
```

**Comment by aghand0ur** [comment]
@alvarolopez the following indeed fixed the issue..why dont u merge it with main branch?
https://github.com/IFCA/DEEPaaS/commit/ea8233ec36de148018cb90026d195756f0cb719e
